#!/usr/bin/bash

# Guards
if [ -z "$DBOX_HOME_FOLDER" ]; then
	echo "ERROR! The DBOX_HOME_FOLDER must be set to the directory you want the containers to base their home directory in."
	exit 2
elif [ -z "$DBOX_PROVISION_SCRIPT_LOC" ]; then
	echo "ERROR! DBOX_PROVISION_SCRIPT_LOC must be set to provision the container once initialized."
	exit 2
fi


dbox_help() {
	  printf "Thin wrapper around distrobox that makes the most commonly used commands painless.\n\nUSAGE:\tdbox <COMMAND> <ARGS>\n\nCOMMANDS:\n\tcreate: Creates a distrobox with the given name at DBOX_HOME_FOLDER.\n\tenter: Enters into the given container."
}

# Bash is pretty weird, so $1 here means the first argument passed to this function, not the first argument passed to the script
dbox_create() {
	local INTERNAL_HOME_FOLDER="$DBOX_HOME_FOLDER/$1" 
	
	echo "Making home folder..."
	mkdir -p "$INTERNAL_HOME_FOLDER" 2>/dev/null

	echo "Copying provision script..."
	cp "$DBOX_PROVISION_SCRIPT_LOC" "$INTERNAL_HOME_FOLDER"
	
	echo "Copying neovim project script..."
	cp "$HOME/Documents/4.archives/2.scripts/nv" "$INTERNAL_HOME_FOLDER/.local/scripts/nv"
	
	distrobox create -n "$1" -H "$INTERNAL_HOME_FOLDER" --additional-packages "git neovim ripgrep zoxide eza bat clang zig nodejs"

	distrobox enter -nw "$1" -- zsh provision
}

dbox_enter() {
	distrobox enter -nw "$1"
}

# TODO: The logic is not in the right order. This will skip any extra arguments that need to be passed onto distrobox and instead exit silently.

if [ $# -eq 1 ]; then
	if [ $1 == "help" ]; then
		dbox_help
		exit 0
	else
		echo "Passing commands on to distrobox..."
		distrobox "$@"
		exit 0
	fi
elif ! [ $# -eq 2 ]; then
	echo "Invalid use of the command, please type help to check usage."
	exit 2
else
	if [ $1 == "create" ]; then
		if ! [ $2 == "" ]; then
			dbox_create "$2"
			exit 0
		else
			echo "Cannot create a container with an empty name"
			exit 2
		fi
	elif [ $1 == "enter" ]; then
		if ! [ $2 == "" ]; then
			dbox_enter "$2"
			exit 0
		else
			echo "Cannot enter a container without a name"
			exit 2
		fi
	fi
fi
